### ISSUE TITLE
Periodic: Editor_ComponentCommands_Works consistently fails on Linux Periodic test runs

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#11023]
**Describe the bug**
Editor_ComponentCommands_Works consistently fails on Linux Periodic test runs.

**Failed Jenkins Job Information:**
https://jenkins.build.o3de.org/blue/rest/organizations/jenkins/pipelines/O3DE_periodic-incremental-daily/branches/development/runs/57/nodes/428/steps/434/log/?start=0

```
[2022-08-02T06:42:32.028Z]     pytest.fail(error_str)
[2022-08-02T06:42:32.028Z] E   Failed: Test Editor_ComponentCommands_Works:
[2022-08-02T06:42:32.028Z] E   Test FAILED
[2022-08-02T06:42:32.028Z] E   ------------
[2022-08-02T06:42:32.028Z] E   |  Output  |
[2022-08-02T06:42:32.028Z] E   ------------
[2022-08-02T06:42:32.028Z] E   Starting test test...
[2022-08-02T06:42:32.028Z] E   Test test finished.
[2022-08-02T06:42:32.028Z] E   Report:
[2022-08-02T06:42:32.028Z] E   [FAILED ] Failure: n
[2022-08-02T06:42:32.028Z] E   EXCEPTION raised:
[2022-08-02T06:42:32.028Z] E     Traceback (most recent call last):
[2022-08-02T06:42:32.028Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 305, in start_test
[2022-08-02T06:42:32.028Z] E         test_function()
[2022-08-02T06:42:32.028Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonBindings/tests/Editor_ComponentCommands_Works.py", line 92, in test
[2022-08-02T06:42:32.028Z] E         BaseClass.check_result(commentsCount == 2, "Entity has two Comment components")
[2022-08-02T06:42:32.028Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonBindings/tests/Editor_TestClass.py", line 16, in check_result
[2022-08-02T06:42:32.028Z] E         raise Exception(msg + " : FAILED")
[2022-08-02T06:42:32.028Z] E     Exception: Entity has two Comment components : FAILED
[2022-08-02T06:42:32.028Z] E   Test result:  FAILURE
[2022-08-02T06:42:32.028Z] E   JSON_START({"name": "Editor_ComponentCommands_Works", "success": false, "exception": "Traceback (most recent call last):\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py\", line 305, in start_test\n      test_function()\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonBindings/tests/Editor_ComponentCommands_Works.py\", line 92, in test\n      BaseClass.check_result(commentsCount == 2, \"Entity has two Comment components\")\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonBindings/tests/Editor_TestClass.py\", line 16, in check_result\n      raise Exception(msg + \" : FAILED\")\n  Exception: Entity has two Comment components : FAILED", "output": "Test test finished.\nReport:\n[FAILED ] Failure: n\nEXCEPTION raised:\n  Traceback (most recent call last):\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py\", line 305, in start_test\n      test_function()\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonBindings/tests/Editor_ComponentCommands_Works.py\", line 92, in test\n      BaseClass.check_result(commentsCount == 2, \"Entity has two Comment components\")\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonBindings/tests/Editor_TestClass.py\", line 16, in check_result\n      raise Exception(msg + \" : FAILED\")\n  Exception: Entity has two Comment components : FAILED\nTest result:  FAILURE"})JSON_END
```

**Comment by jckand-amzn** [comment]
Test failure has been root caused to #11032. Skipping test in #11053 .
