### ISSUE TITLE
[Linux] : Building from a remote template from Project Manager using SNAP crashes during build

### ISSUE THREAD

**Issue by spham-amzn** [o3de/o3de#16642]
**Describe the bug**

Using the snap package at: https://o3debinaries.org/23.10.0/Linux/o3de_23.10.0_amd64.snap, when creating a new project based on a 'Remote Template. will crash when trying to build the new project. Inspecting the log, it looks like a python dependency for 'resolvelib' is missing

```
-- Using package /home/o3de/.o3de/3rdParty/packages/v-hacd-2.3-1a49edf-rev1-linux
-- Using package /home/o3de/.o3de/3rdParty/packages/OpenMesh-8.1-rev3-linux
CMake Warning at /snap/o3de/x1/23.10.0/cmake/Subdirectories.cmake:218 (message):
  Dependency resolution failed.

    If needed, set the O3DE_DISABLE_GEM_DEPENDENCY_RESOLUTION variable to bypass dependency resolution.
    Error: Traceback (most recent call last):
    File "/snap/o3de/x1/23.10.0/scripts/o3de/o3de/cmake.py", line 22, in <module>
      from o3de import manifest, utils, compatibility
    File "/snap/o3de/x1/23.10.0/scripts/o3de/o3de/manifest.py", line 19, in <module>
      from o3de import validation, utils, repo, compatibility
    File "/snap/o3de/x1/23.10.0/scripts/o3de/o3de/compatibility.py", line 17, in <module>
      from resolvelib import (

  ModuleNotFoundError: No module named 'resolvelib'

Call Stack (most recent call first):
  /snap/o3de/x1/23.10.0/cmake/Subdirectories.cmake:356 (resolve_gem_dependencies)
  /snap/o3de/x1/23.10.0/cmake/Subdirectories.cmake:438 (get_all_external_subdirectories_for_o3de_object)
  /snap/o3de/x1/23.10.0/cmake/Subdirectories.cmake:470 (get_external_subdirectories_in_use)
  /snap/o3de/x1/23.10.0/CMakeLists.txt:87 (add_subdirectory_on_external_subdirs)
```

**Assets required**
N/A

**Steps to reproduce**
1. On a clean ubuntu 22.05 machine, install all the prequisites ( refer to https://snapcraft.io/o3de )
2. Download the stabilization snap package from https://o3debinaries.org/23.10.0/Linux/o3de_23.10.0_amd64.snap and install with `sudo snap install --classic --dangerous o3de_23.10.0_amd64.snap`
3. Launch `o3de`
4. Click on `New Project`->`Create New Project`
5. Click on 'Add remote template` and then enter in `https://github.com/o3de/o3de-extras.git` for the remote URL
6. Click on 'Add'
7. Click on 'Create Project'
8. Click on 'Build Project' for the new project

**Expected behavior**
The project builds without any issue

**Actual behavior**
The project manager shuts down

**Screenshots/Video**

https://github.com/o3de/o3de/assets/82231385/bec7d928-caa0-4fea-979e-3e2908e387f5

**Found in Branch**
stabilization/2310

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
85891e13e7485f3385d83a49f69828b8f07889bf

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version Ubuntu 22.04
 - CPU : N/A
 - GPU: N/A
 - Memory : N/A

**Comment by spham-amzn** [comment]
Fixed with https://github.com/o3de/o3de/pull/16646
