### ISSUE TITLE
Project Exporter: Profile Export Fails to Create PAK

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#16868]
Using project exporter to export a profile build, will fail to generate pak files.

**Steps to reproduce**
1. Export a project using profile configuration
````
~/o3de/scripts/o3de.sh export-project -es ~/multiplayersample/ExportScripts/export_mps.py -out ~/MPSExport_Profilex86 -gl -assets -nogame -noserver -nounified -pl linux -cfg profile -ll INFO 
```
**Expected behavior**
Export succeeds

**Actual behavior**
```
[INFO] root: Setting project to ( /home/ec2-user/multiplayersample ).
[INFO] root: Creating Bundle ( /home/ec2-user/multiplayersample/build/asset_bundling/Bundles/game_linux.pak )...
[INFO] root:
[INFO] root: [WARN] - Archive:
[INFO] root: ZD_ERROR_NO_CDR: Cannot find Central Directory Record in pak. This is either not a pak file, or a pak file without Central Directory. It does not mean that the data is permanently lost, but it may be severely damaged. Please repair the file with external tools, there may be enough information left to recover the file completely.
[INFO] root:
[INFO] root: [WARN] - Archive:
[INFO] root: ZD_ERROR_IO_FAILED: Could not open file "/home/ec2-user/multiplayersample/build/asset_bundling/Bundles/game_linux.pak_temp" in binary mode for reading
[INFO] root:
[INFO] root: [ERROR] - ArchiveComponent:
[INFO] root: Failed to open archive file '/home/ec2-user/multiplayersample/build/asset_bundling/Bundles/game_linux.pak_temp'
[INFO] root:
[INFO] root: [ERROR] - AssetBundle:
[INFO] root: Failed to insert files into bundle (/home/ec2-user/multiplayersample/build/asset_bundling/Bundles/game_linux.pak_temp).
[INFO] root:
[INFO] root:
[INFO] root: [ERROR] - AssetBundler:
[INFO] root: Unable to create bundle, target Bundle file path is ( /home/ec2-user/multiplayersample/build/asset_bundling/Bundles/game_linux.pak ).
[INFO] root:
[INFO] root: Terminating process '/home/ec2-user/multiplayersample/build/tools/bin/profile/AssetBundlerBatch' with PID(130628)
[INFO] root: process '/home/ec2-user/multiplayersample/build/tools/bin/profile/AssetBundlerBatch' with PID(130628) terminated with exit code 1
[ERROR] o3de.utils: Failed to run script '/home/ec2-user/multiplayersample/ExportScripts/export_mps.py'. Here is the stacktrace:
Traceback (most recent call last):
  File "/home/ec2-user/o3de/scripts/o3de/o3de/utils.py", line 190, in load_and_execute_script
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ec2-user/multiplayersample/ExportScripts/export_mps.py", line 246, in <module>
    export_multiplayer_sample(ctx=o3de_context,
  File "/home/ec2-user/multiplayersample/ExportScripts/export_mps.py", line 128, in export_multiplayer_sample
    expected_bundles_path = exp.bundle_assets(ctx=ctx,
  File "/home/ec2-user/o3de/scripts/o3de/o3de/export_project.py", line 660, in bundle_assets
    raise RuntimeError(f"Error generating game bundle for {bundles_path / f'game_{selected_platform}.pak'}")
RuntimeError: Error generating game bundle for /home/ec2-user/multiplayersample/build/asset_bundling/Bundles/game_linux.pak
[INFO] o3de: Completed with issues: result 1
```


**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
8d89ec32f88357791283da75424e26197bd6a545
October 3rd 2023

**Desktop/Device (please complete the following information):**
x86 Amazon Linux 2023

**Comment by lumberyard-employee-dm** [comment]
The PAK file exporting should be using the profile AssetBundlerBatch even for exporting a release project.
But based on the error posted, it looks like the PAK file is incompatible or corrupted.
I don't believe any release specific code should be causing an issue in this case
