### ISSUE TITLE
InputBindings_Add_Remove_Input_Events failure of in AutomatedTesting::EditorTests_Main.main

### ISSUE THREAD

**Issue by amzn-changml** [o3de/o3de#17789]
**Describe the bug**
The automation test `test_InputBindings_Add_Remove_Input_Events` is consistently failing in the `AutomatedTesting::EditorTests_Main.main`

**Assets required**
Logs can be found here: https://jenkins.build.o3de.org/blue/rest/organizations/jenkins/pipelines/O3DE/branches/development/runs/4971/nodes/809/steps/816/log/?start=0

**Steps to reproduce**
1. Build O3DE with the profile target
2. Run `ctest` with `ctest -j16 -C profile --output-on-failure -L "(SUITE_smoke|SUITE_main)" -LE "(REQUIRES_gpu|REQUIRES_tiaf)" -T Test --no-tests=error`

**Expected behavior**
All test pass

**Actual behavior**
A timeout exception is raised for the specific test, resulting in failure

**Screenshots/Video**
N/A

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
75bbcc1ae57670ca5e2042e8a6d10cd26fc9e07d

**Desktop/Device (please complete the following information):**
 - Device: AWS EC2
 - OS: Windows Server 
 - Version: 2022 (eqv to Windows 11)
 - CPU: AMD EPYC 7R13
 - GPU: N/A
 - Memory 32GB

**Additional context**
Log message as follows:

```
[2024-04-20T17:26:53.218Z] [editor_test.log]  
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> (python_test) - 
[2024-04-20T17:26:53.218Z] [editor_test.log]  
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> (python) - Running automated test: D:/workspace/o3de/AutomatedTesting/Gem/PythonTests/editor/EditorScripts/InputBindings_Add_Remove_Input_Events.py (testcase AutomatedTesting/Gem/PythonTests/editor/TestSuite_Main.py::TestAutomationNoAutoTestMode::test_InputBindings_Add_Remove_Input_Events[windows-AutomatedTesting-windows_editor])
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> (python_test) - Info: Open level /Base
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> (python_test) - 
[2024-04-20T17:26:53.218Z] [editor_test.log]  
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> Opening level levels/base/base.spawnable
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> Loading from D:/workspace/o3de/AutomatedTesting/Levels/Base/Base.prefab...
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> ---- Start: Game Engine level load
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> Loading map 'D:/workspace/o3de/AutomatedTesting/Levels/Base' into engine...
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> ---- End: Game Engine level load (0 seconds)
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> ---- Start: Post Load
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> ---- End: Post Load (0 seconds)
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> [LevelLoadTime] Level D:/workspace/o3de/AutomatedTesting/Levels/Base loaded in 0 seconds
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> -----------------------------------------------------------
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> Successfully opened document D:/workspace/o3de/AutomatedTesting/Levels/Base/Base.prefab
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> Level loading time: 0.01 seconds
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:23> -----------------------------------------------------------
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:24> (python_test) - Success: Successfully opened the Asset Editor
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:24> (python_test) - 
[2024-04-20T17:26:53.218Z] [editor_test.log]  
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:24> (python_test) - Success: Successfully added event groups via +
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:24> (python_test) - 
[2024-04-20T17:26:53.218Z] [editor_test.log]  
[2024-04-20T17:26:53.218Z] [editor_test.log]  <17:26:26> (python_test) - Test InputBindings_Add_Remove_Input_Events finished.
[2024-04-20T17:26:53.218Z] [editor_test.log]  Report:
[2024-04-20T17:26:53.218Z] [editor_test.log]  [SUCCESS] Success: Successfully opened the Asset Editor
[2024-04-20T17:26:53.218Z] [editor_test.log]  [SUCCESS] Success: Successfully added event groups via +
[2024-04-20T17:26:53.219Z] [editor_test.log]  EXCEPTION raised:
[2024-04-20T17:26:53.219Z] [editor_test.log]    Traceback (most recent call last):
[2024-04-20T17:26:53.219Z] [editor_test.log]      File "D:\workspace\o3de\AutomatedTesting\Gem\PythonTests\EditorPythonTestTools\editor_python_test_tools\utils.py", line 341, in start_test
[2024-04-20T17:26:53.219Z] [editor_test.log]        test_function()
[2024-04-20T17:26:53.219Z] [editor_test.log]      File "D:/workspace/o3de/AutomatedTesting/Gem/PythonTests/editor/EditorScripts/InputBindings_Add_Remove_Input_Events.py", line 155, in InputBindings_Add_Remove_Input_Events
[2024-04-20T17:26:53.219Z] [editor_test.log]        run_test()
[2024-04-20T17:26:53.219Z] [editor_test.log]      File "D:\workspace\o3de\Gems\QtForPython\Editor\Scripts\pyside_utils.py", line 257, in wrapper
[2024-04-20T17:26:53.219Z] [editor_test.log]        return run_async(result)
[2024-04-20T17:26:53.219Z] [editor_test.log]      File "D:\workspace\o3de\Gems\QtForPython\Editor\Scripts\pyside_utils.py", line 236, in run_async
[2024-04-20T17:26:53.219Z] [editor_test.log]        return awaitable.result()
[2024-04-20T17:26:53.219Z] [editor_test.log]      File "D:/workspace/o3de/AutomatedTesting/Gem/PythonTests/editor/EditorScripts/InputBindings_Add_Remove_Input_Events.py", line 130, in run_test
[2024-04-20T17:26:53.219Z] [editor_test.log]        success = await pyside_utils.wait_for_condition(lambda: "2 elements" in
[2024-04-20T17:26:53.219Z] [editor_test.log]    pyside_utils.EventLoopTimeoutException
[2024-04-20T17:26:53.219Z] [editor_test.log]  Test result:  FAILURE
[2024-04-20T17:26:53.219Z] [editor_test.log]  JSON_START({"name": "InputBindings_Add_Remove_Input_Events", "success": false, "exception": "Traceback (most recent call last):\n    File \"D:\\workspace\\o3de\\AutomatedTesting\\Gem\\PythonTests\\EditorPythonTestTools\\editor_python_test_tools\\utils.py\", line 341, in start_test\n      test_function()\n    File \"D:/workspace/o3de/AutomatedTesting/Gem/PythonTests/editor/EditorScripts/InputBindings_Add_Remove_Input_Events.py\", line 155, in InputBindings_Add_Remove_Input_Events\n      run_test()\n    File \"D:\\workspace\\o3de\\Gems\\QtForPython\\Editor\\Scripts\\pyside_utils.py\", line 257, in wrapper\n      return run_async(result)\n    File \"D:\\workspace\\o3de\\Gems\\QtForPython\\Editor\\Scripts\\pyside_utils.py\", line 236, in run_async\n      return awaitable.result()\n    File \"D:/workspace/o3de/AutomatedTesting/Gem/PythonTests/editor/EditorScripts/InputBindings_Add_Remove_Input_Events.py\", line 130, in run_test\n      success = await pyside_utils.wait_for_condition(lambda: \"2 elements\" in\n  pyside_utils.EventLoopTimeoutException", "output": "Test InputBindings_Add_Remove_Input_Events finished.\nReport:\n[SUCCESS] Success: Successfully opened the Asset Editor\n[SUCCESS] Success: Successfully added event groups via +\nEXCEPTION raised:\n  Traceback (most recent call last):\n    File \"D:\\workspace\\o3de\\AutomatedTesting\\Gem\\PythonTests\\EditorPythonTestTools\\editor_python_test_tools\\utils.py\", line 341, in start_test\n      test_function()\n    File \"D:/workspace/o3de/AutomatedTesting/Gem/PythonTests/editor/EditorScripts/InputBindings_Add_Remove_Input_Events.py\", line 155, in InputBindings_Add_Remove_Input_Events\n      run_test()\n    File \"D:\\workspace\\o3de\\Gems\\QtForPython\\Editor\\Scripts\\pyside_utils.py\", line 257, in wrapper\n      return run_async(result)\n    File \"D:\\workspace\\o3de\\Gems\\QtForPython\\Editor\\Scripts\\pyside_utils.py\", line 236, in run_async\n      return awaitable.result()\n    File \"D:/workspace/o3de/AutomatedTesting/Gem/PythonTests/editor/EditorScripts/InputBindings_Add_Remove_Input_Events.py\", line 130, in run_test\n      success = await pyside_utils.wait_for_condition(lambda: \"2 elements\" in\n  pyside_utils.EventLoopTimeoutException\nTest result:  FAILURE"})JSON_END
[2024-04-20T17:26:53.219Z] [editor_test.log]  
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> (python_test) - 
[2024-04-20T17:26:53.219Z] [editor_test.log]  
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> [Error] (python_test) - Traceback (most recent call last):
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> [Error] (python_test) -   File "D:/workspace/o3de/AutomatedTesting/Gem/PythonTests/editor/EditorScripts/InputBindings_Add_Remove_Input_Events.py", line 161, in <module>
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> [Error] (python_test) -     
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> [Error] (python_test) - Report.start_test(InputBindings_Add_Remove_Input_Events)
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> [Error] (python_test) - 
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> [Error] (python_test) -   File "D:\workspace\o3de\AutomatedTesting\Gem\PythonTests\EditorPythonTestTools\editor_python_test_tools\utils.py", line 350, in start_test
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> [Error] (python_test) -     
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> [Error] (python_test) - assert success, f"Test {test_function.__name__} failed"
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> [Error] (python_test) - 
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> [Error] (python_test) - AssertionError
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> [Error] (python_test) - : 
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> [Error] (python_test) - Test InputBindings_Add_Remove_Input_Events failed
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> [Error] (python_test) - 
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> [Warning] (python) - Detected script failure in Python script(D:/workspace/o3de/AutomatedTesting/Gem/PythonTests/editor/EditorScripts/InputBindings_Add_Remove_Input_Events.py); return code -1!
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> [Error] (python_test) - EXCEPTION: Detected script failure in Python script(D:/workspace/o3de/AutomatedTesting/Gem/PythonTests/editor/EditorScripts/InputBindings_Add_Remove_Input_Events.py); return code -1!
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> (Exit) - Called Terminate() with exit code: 0xf
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> (Exit) - D:\workspace\o3de\Code\Framework\AzCore\AzCore\Debug\Trace.cpp (297) : AZ::Debug::Trace::Terminate
[2024-04-20T17:26:53.219Z] [editor_test.log]  
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> (Exit) - D:\workspace\o3de\Code\Editor\CryEdit.cpp (1507) : CCryEditApp::RunInitPythonScript
[2024-04-20T17:26:53.219Z] [editor_test.log]  
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> (Exit) - D:\workspace\o3de\Code\Editor\CryEdit.cpp (1766) : CCryEditApp::InitInstance
[2024-04-20T17:26:53.219Z] [editor_test.log]  
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> (Exit) - D:\workspace\o3de\Code\Editor\CryEdit.cpp (3489) : CryEditMain
[2024-04-20T17:26:53.219Z] [editor_test.log]  
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> (Exit) - D:\workspace\o3de\Code\Editor\main.cpp (31) : main
[2024-04-20T17:26:53.219Z] [editor_test.log]  
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> (Exit) - D:\github\3p-package-source\package-system\Qt\temp\src\qtbase\src\winmain\qtmain_win.cpp (97) : WinMain
[2024-04-20T17:26:53.219Z] [editor_test.log]  
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> (Exit) - D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (288) : __scrt_common_main_seh
[2024-04-20T17:26:53.219Z] [editor_test.log]  
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> (Exit) - 00007FFBCA5F4CB0 (KERNEL32) : BaseThreadInitThunk
[2024-04-20T17:26:53.219Z] [editor_test.log]  
[2024-04-20T17:26:53.219Z] [editor_test.log]  <17:26:26> (Exit) - 00007FFBCBCBE8AB (ntdll) : RtlUserThreadStart
[2024-04-20T17:26:53.219Z] [editor_test.log]
[2024-04-20T17:26:53.219Z] = 1 failed, 22 passed, 1 skipped, 2 deselected, 1 warning in 223.11s (0:03:43) =
```

**Comment by lsemp3d** [comment]
Closed by #17792
