### ISSUE TITLE
Error exporting android project from O3DE SDK

### ISSUE THREAD

**Issue by spham-amzn** [o3de/o3de#18241]
**Describe the bug**
When attempting to export a project to android from the O3DE SDK, an error occurs during the android export script.

**Assets required**
Default assets from a project generated from the DefaultProject template

**Steps to reproduce**
1. Intall the O3DE SDK and Launch the Project Manager
2. Create a new Project with the Default Project template
3. Open the Editor, make sure that the assets are compiled and the level opens up
4. Go back to the Project Manager
5. Under the project tile, click on the menu context button and export settings
6. Set `DefaultLevel` in the `LevelNames`
7. Make sure 'Build Assets' is enabled
8. Click Save
9. Click on the menu context button and Export Launcher->Android

**Expected behavior**
The android project is created

**Actual behavior**
The process fails with a python stack trace

**Found in Branch**
stabilization/2409 

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
N/A  (SDK installer)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU N/A
 - GPU N/A
 - Memory 32 GB

**Additional context**
Stack trace of error:
```
[ERROR] o3de.utils: Failed to run script 'C:\O3DE\24.09\scripts\o3de\ExportScripts\export_source_android.py'. Here is the stacktrace: 

Traceback (most recent call last):
  File "C:\O3DE\24.09\scripts\o3de\o3de\utils.py", line 190, in load_and_execute_script
    spec.loader.exec_module(script_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\O3DE\24.09\scripts\o3de\ExportScripts\export_source_android.py", line 255, in <module>
    export_source_android_run_command(o3de_context, args, export_config, o3de_logger)
  File "C:\O3DE\24.09\scripts\o3de\ExportScripts\export_source_android.py", line 207, in export_source_android_run_command
    export_source_android_project(ctx=o3de_context,
  File "C:\O3DE\24.09\scripts\o3de\ExportScripts\export_source_android.py", line 91, in export_source_android_project
    android_sdk_home = pathlib.Path(android_project_config.get_value(key=android_support.SETTINGS_SDK_ROOT.key))
  File "C:\Users\spham\.o3de\Python\packages\python-3.10.13-rev1-windows\python\lib\pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "C:\Users\spham\.o3de\Python\packages\python-3.10.13-rev1-windows\python\lib\pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\spham\.o3de\Python\packages\python-3.10.13-rev1-windows\python\lib\pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[INFO] o3de: Completed with issues: result 1
```

Full Log:
[ExportError.log](https://github.com/user-attachments/files/16694795/ExportError.log)

**Comment by spham-amzn** [comment]
Root cause of this particular issue is that the export process does not validate if the android settings were setup properly.

**Comment by spham-amzn** [comment]
The export script needs to run `c:\O3de\24.09\scripts\o3de.bat android-configure --validate` and report any issues
