### ISSUE TITLE
export-project script not working because of missing dependency (o3de sdk)

### ISSUE THREAD

**Issue by pijaro** [o3de/o3de#18246]
**Describe the bug**
When using O3DE-SDK, the `scripts/o3de.sh export-project` throws an error that tkinter has an unresolved dependency.

**Steps to reproduce**
1. Build O3DE sdk (stabilization/2409)
2. Run the `o3de.sh export-project` script on some project 
5. See error

**Expected behavior**
The script works and continues to build a project.

**Actual behavior**
Error is thrown:

```bash
Traceback (most recent call last):
  File "/home/developer/o3de_sdks/stabilization_2409/scripts/o3de.py", line 108, in <module>
    ret = known_args.func(known_args, unknown_args) if hasattr(known_args, 'func') else 1
  File "/home/developer/o3de_sdks/stabilization_2409/scripts/o3de/o3de/export_project.py", line 402, in _run_export_script
    export_project_ui.MainWindow(export_config, is_o3de_sdk).configure_settings()
  File "/home/developer/o3de_sdks/stabilization_2409/scripts/o3de/o3de/ui/export_project.py", line 35, in __init__
    super().__init__()
  File "/home/developer/.o3de/Python/packages/python-3.10.13-rev2-linux/python/lib/python3.10/tkinter/tix.py", line 221, in __init__
    self.tk.eval('package require Tix')
_tkinter.TclError: can't find package Tix
```

**Found in Branch**
https://github.com/o3de/o3de/tree/stabilization/2409

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
08bc7753490bb617f12d22d1e7c6e5f7a96a128f

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Ubuntu
 - Version 22

**Comment by spham-amzn** [comment]
This was a missing requirement, and fixed with 2 PRs:

https://github.com/o3de/o3de.org/pull/2580 

https://github.com/o3de/o3de/pull/18252
