### ISSUE TITLE
24.09 Release - _tkinter.TclError: can't find package Tix

### ISSUE THREAD

**Issue by michalpelka** [o3de/o3de#18291]
### Bug Description

I've created a project using a o3de debian package downloaded 5.09.2024.
I've built project and tried option "Open Export settings" from "hamgurger" button here:
![image](https://github.com/user-attachments/assets/f76b115e-42d4-4d18-8426-9f38f91882a6)
It failed.

### Assets-Required

o3de debian package

### Steps to Reproduce

As explained in description.

### Expected Behavior

Something else than error in console

### Actual Behavior

ProjectManager produced this output (project mananger did not crash):
```
rojectManager: Will start the Export Configuration Panel with the following command:
/opt/O3DE/24.09/python/python.sh /opt/O3DE/24.09/scripts/o3de.py export-project -pp /home/michalpelka/O3DE/Projects/Ros2Project --configure
1.10.1
Traceback (most recent call last):
  File "/opt/O3DE/24.09/scripts/o3de.py", line 108, in <module>
    ret = known_args.func(known_args, unknown_args) if hasattr(known_args, 'func') else 1
  File "/opt/O3DE/24.09/scripts/o3de/o3de/export_project.py", line 402, in _run_export_script
    export_project_ui.MainWindow(export_config, is_o3de_sdk).configure_settings()
  File "/opt/O3DE/24.09/scripts/o3de/o3de/ui/export_project.py", line 35, in __init__
    super().__init__()
  File "/home/michalpelka/.o3de/Python/packages/python-3.10.13-rev2-linux/python/lib/python3.10/tkinter/tix.py", line 221, in __init__
    self.tk.eval('package require Tix')
_tkinter.TclError: can't find package Tix
ProjectManager: Will start the Export Configuration Panel with the following command:
/opt/O3DE/24.09/python/python.sh /opt/O3DE/24.09/scripts/o3de.py export-project -pp /home/michalpelka/O3DE/Projects/Ros2Project --configure
1.10.1
Traceback (most recent call last):
  File "/opt/O3DE/24.09/scripts/o3de.py", line 108, in <module>
    ret = known_args.func(known_args, unknown_args) if hasattr(known_args, 'func') else 1
  File "/opt/O3DE/24.09/scripts/o3de/o3de/export_project.py", line 402, in _run_export_script
    export_project_ui.MainWindow(export_config, is_o3de_sdk).configure_settings()
  File "/opt/O3DE/24.09/scripts/o3de/o3de/ui/export_project.py", line 35, in __init__
    super().__init__()
  File "/home/michalpelka/.o3de/Python/packages/python-3.10.13-rev2-linux/python/lib/python3.10/tkinter/tix.py", line 221, in __init__
    self.tk.eval('package require Tix')
_tkinter.TclError: can't find package Tix
```

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/f94c2bb8-64fe-425e-a1c9-009ae5006869)

### Found In Branch

debian package

### Commit ID From

I do not know which commit was used to build debian package

### Desktop/Device

Ubuntu 22.04

### Additional Context

I've used ROS2 Project template and registered all gems and templates from o3de-extras/stabilization/2409

**Comment by michalpelka** [comment]
Duplicate to https://github.com/o3de/o3de/issues/18246
