### ISSUE TITLE
It is not possible to create new Projects

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#3443]
**Describe the bug**
It is not possible to create a new Project after following the [building instruction for the _Pre-built SDK engine_](https://o3deorg.netlify.app/docs/welcome-guide/setup/setup-from-github/).
When trying to create a Project through the Project Manager, the "Failed to create project" error occurs. If doing so through the command line, the following error is displayed:
```
C:\o3de-install>scripts\o3de.bat create-project --project-path C:\Users\GPC-610\.o3de\Projects\Testing
Traceback (most recent call last):
  File "C:\o3de-install\scripts\o3de\o3de\engine_template.py", line 140, in _transform_copy
    with open(source_file, 'r') as s:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\o3de-install\\Templates\\DefaultProject\\Template\\CMakeLists.txt'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\o3de-install\scripts\o3de.py", line 88, in <module>
    ret = the_args.func(the_args)
  File "C:\o3de-install\scripts\o3de\o3de\engine_template.py", line 2096, in _run_create_project
    args.module_id)
  File "C:\o3de-install\scripts\o3de\o3de\engine_template.py", line 1587, in create_project
    keep_license_text):
  File "C:\o3de-install\scripts\o3de\o3de\engine_template.py", line 307, in _instantiate_template
    keep_license_text)
  File "C:\o3de-install\scripts\o3de\o3de\engine_template.py", line 194, in _execute_template_json
    _transform_copy(in_file, out_file, replacements, keep_license_text)
  File "C:\o3de-install\scripts\o3de\o3de\engine_template.py", line 151, in _transform_copy
    shutil.copy(source_file, destination_file)
  File "C:\o3de-install\python\runtime\python-3.7.10-rev1-windows\python\lib\shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\o3de-install\python\runtime\python-3.7.10-rev1-windows\python\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\o3de-install\\Templates\\DefaultProject\\Template\\CMakeLists.txt'

```

**To Reproduce**
1. Follow the [_Pre-built SDK engine_ instruction](https://o3deorg.netlify.app/docs/welcome-guide/setup/setup-from-github/).
2. Navigate to C:\o3de-install\bin\Windows\profile and launch editor.exe.
3. Attempt to create a new Project.

**Expected behavior**
A new Project is created successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/86953108/130792594-778a5c11-f870-40a0-9403-bd29f55b4e6d.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Comment by amznestebanpapp** [comment]
@LB-TomaszSerwanski my apologies, this was me. You can checkout `86770deefafd52005ee988ce5ee082e298e3dd3d`, the next commit is where I broke this. Working on a fix.
