### ISSUE TITLE
Generate compilation in python throws an error and cannot open shared object file

### ISSUE THREAD

**Issue by Mobs1024** [o3de/o3de#3956]
Branch: 22e43c9122fdb4debe5edd48b745ac64c7c8bcb2

strange  still throws an errors from python

**To Reproduce**

![2021-09-07_12-54](https://user-images.githubusercontent.com/17591539/132325137-9925c5f2-d683-44a0-a5c1-49d7645871cf.png)

Run terminal

run `:/o3de> cmake -B ${O3DE_PATH}/build/linux_ninja -S ${O3DE_PATH} -G "Ninja Multi-Config" -DCMAKE_C_COMPILER="${C_COMPILER}" -DCMAKE_CXX_COMPILER="${CXX_COMPILER}" -DLY_3RDPARTY_PATH="${LY_3RDPARTY_PATH}" -DLY_PROJECTS="${LY_PROJECTS}" -DLY_UNITY_BUILD=1 "$@"`

errors 

```
:~/o3de> ./ninja-generate.sh 
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/qt-5.15.2-rev5-linux
-- Using package /home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux
-- Using Python 3.7.10 at /home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/bin/python
-- Python: linking /home/xxxxxx/o3de/Tools/LyTestTools into python site-packages...
-- Python: linking /home/xxxxxx/o3de/Tools/LyTestTools into python site-packages... - Failed to install /home/xxxxxx/o3de/Tools/LyTestTools: Obtaining file:///home/xxxxxx/o3de/Tools/LyTestTools
    ERROR: Command errored out with exit status 1:
     command: /home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/xxxxxx/o3de/Tools/LyTestTools/setup.py'"'"'; __file__='"'"'/home/xxxxxx/o3de/Tools/LyTestTools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-z8zzofd7
         cwd: /home/xxxxxx/o3de/Tools/LyTestTools/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/__init__.py", line 19, in <module>
        from setuptools.dist import Distribution
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory
    ----------------------------------------
WARNING: Discarding file:///home/xxxxxx/o3de/Tools/LyTestTools. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 - use CMAKE_MESSAGE_LOG_LEVEL to VERBOSE for more information
-- Python: linking /home/xxxxxx/o3de/Tools/RemoteConsole/ly_remote_console into python site-packages...
-- Python: linking /home/xxxxxx/o3de/Tools/RemoteConsole/ly_remote_console into python site-packages... - Failed to install /home/xxxxxx/o3de/Tools/RemoteConsole/ly_remote_console: Obtaining file:///home/xxxxxx/o3de/Tools/RemoteConsole/ly_remote_console
    ERROR: Command errored out with exit status 1:
     command: /home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/xxxxxx/o3de/Tools/RemoteConsole/ly_remote_console/setup.py'"'"'; __file__='"'"'/home/xxxxxx/o3de/Tools/RemoteConsole/ly_remote_console/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cnm1ig0l
         cwd: /home/xxxxxx/o3de/Tools/RemoteConsole/ly_remote_console/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/__init__.py", line 19, in <module>
        from setuptools.dist import Distribution
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory
    ----------------------------------------
WARNING: Discarding file:///home/xxxxxx/o3de/Tools/RemoteConsole/ly_remote_console. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 - use CMAKE_MESSAGE_LOG_LEVEL to VERBOSE for more information
-- Python: linking /home/xxxxxx/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools into python site-packages...
-- Python: linking /home/xxxxxx/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools into python site-packages... - Failed to install /home/xxxxxx/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools: Obtaining file:///home/xxxxxx/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools
    ERROR: Command errored out with exit status 1:
     command: /home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/xxxxxx/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/setup.py'"'"'; __file__='"'"'/home/xxxxxx/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ftgrssc_
         cwd: /home/xxxxxx/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/__init__.py", line 19, in <module>
        from setuptools.dist import Distribution
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory
    ----------------------------------------
WARNING: Discarding file:///home/xxxxxx/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 - use CMAKE_MESSAGE_LOG_LEVEL to VERBOSE for more information
-- Python: linking /home/xxxxxx/o3de/scripts/o3de into python site-packages...
-- Python: linking /home/xxxxxx/o3de/scripts/o3de into python site-packages... - Failed to install /home/xxxxxx/o3de/scripts/o3de: Obtaining file:///home/xxxxxx/o3de/scripts/o3de
    ERROR: Command errored out with exit status 1:
     command: /home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/xxxxxx/o3de/scripts/o3de/setup.py'"'"'; __file__='"'"'/home/xxxxxx/o3de/scripts/o3de/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wr6x0_y3
         cwd: /home/xxxxxx/o3de/scripts/o3de/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/__init__.py", line 19, in <module>
        from setuptools.dist import Distribution
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory
    ----------------------------------------
WARNING: Discarding file:///home/xxxxxx/o3de/scripts/o3de. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 - use CMAKE_MESSAGE_LOG_LEVEL to VERBOSE for more information
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/RapidJSON-1.1.0-rev1-multiplatform
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/Lua-5.3.5-rev5-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/RapidXML-1.13-rev1-multiplatform
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/zlib-1.2.11-rev2-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/zstd-1.35-multiplatform
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/cityhash-1.1-multiplatform
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/googletest-1.8.1-rev4-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/googlebenchmark-1.5.0-rev2-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/lz4-1.9.3-vcpkg-rev4-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/SQLite-3.32.2-rev3-multiplatform
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/OpenSSL-1.1.1b-rev2-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/expat-2.1.0-multiplatform
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/md5-2.0-multiplatform
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/tiff-4.2.0.15-rev2-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/squish-ccr-deb557d-rev1-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/AWSNativeSDK-1.7.167-rev6-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/assimp-5.0.1-rev11-multiplatform
-- Python: linking /home/xxxxxx/.o3de/3rdParty/packages/assimp-5.0.1-rev11-multiplatform/assimp/port/PyAssimp into python site-packages...
-- Python: linking /home/xxxxxx/.o3de/3rdParty/packages/assimp-5.0.1-rev11-multiplatform/assimp/port/PyAssimp into python site-packages... - Failed to install /home/xxxxxx/.o3de/3rdParty/packages/assimp-5.0.1-rev11-multiplatform/assimp/port/PyAssimp: Obtaining file:///home/xxxxxx/.o3de/3rdParty/packages/assimp-5.0.1-rev11-multiplatform/assimp/port/PyAssimp
    ERROR: Command errored out with exit status 1:
     command: /home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/xxxxxx/.o3de/3rdParty/packages/assimp-5.0.1-rev11-multiplatform/assimp/port/PyAssimp/setup.py'"'"'; __file__='"'"'/home/xxxxxx/.o3de/3rdParty/packages/assimp-5.0.1-rev11-multiplatform/assimp/port/PyAssimp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-hms6bqni
         cwd: /home/xxxxxx/.o3de/3rdParty/packages/assimp-5.0.1-rev11-multiplatform/assimp/port/PyAssimp/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/__init__.py", line 19, in <module>
        from setuptools.dist import Distribution
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory
    ----------------------------------------
WARNING: Discarding file:///home/xxxxxx/.o3de/3rdParty/packages/assimp-5.0.1-rev11-multiplatform/assimp/port/PyAssimp. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 - use CMAKE_MESSAGE_LOG_LEVEL to VERBOSE for more information
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/xxhash-0.7.4-rev1-multiplatform
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/pybind11-2.4.3-rev2-multiplatform
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/astc-encoder-3.2-rev1-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/etc2comp-9cd0f9cae0-rev1-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/PVRTexTool-4.24.0-rev4-multiplatform
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/ISPCTexComp-36b80aa-rev1-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/ilmbase-2.3.0-rev4-multiplatform
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/mcpp-2.7.2_az.1-rev1-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/DirectXShaderCompilerDxc-1.6.2104-o3de-rev3-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/SPIRVCross-2021.04.29-rev1-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/azslc-1.7.23-rev2-linux
-- Python: linking /home/xxxxxx/o3de/Gems/Atom/RPI/Tools into python site-packages...
-- Python: linking /home/xxxxxx/o3de/Gems/Atom/RPI/Tools into python site-packages... - Failed to install /home/xxxxxx/o3de/Gems/Atom/RPI/Tools: Obtaining file:///home/xxxxxx/o3de/Gems/Atom/RPI/Tools
    ERROR: Command errored out with exit status 1:
     command: /home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/xxxxxx/o3de/Gems/Atom/RPI/Tools/setup.py'"'"'; __file__='"'"'/home/xxxxxx/o3de/Gems/Atom/RPI/Tools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vzqfrb5g
         cwd: /home/xxxxxx/o3de/Gems/Atom/RPI/Tools/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/__init__.py", line 19, in <module>
        from setuptools.dist import Distribution
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory
    ----------------------------------------
WARNING: Discarding file:///home/xxxxxx/o3de/Gems/Atom/RPI/Tools. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
 - use CMAKE_MESSAGE_LOG_LEVEL to VERBOSE for more information
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/freetype-2.10.4.16-linux
-- Python: Getting/Checking packages listed in /home/xxxxxx/o3de/Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/requirements.txt
-- Python: Getting/Checking packages listed in /home/xxxxxx/o3de/Gems/AtomLyIntegration/TechnicalArt/DccScriptingInterface/requirements.txt - Failed to fetch / update python dependencies: Collecting cachetools==4.2.1
  Using cached cachetools-4.2.1-py3-none-any.whl (12 kB)
Collecting certifi==2020.12.5
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting click==7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting dynaconf==3.1.4
  Using cached dynaconf-3.1.4-py2.py3-none-any.whl (197 kB)
Collecting hashids==1.3.1
  Using cached hashids-1.3.1-py2.py3-none-any.whl (6.6 kB)
Collecting pathlib==1.0.1
  Using cached pathlib-1.0.1.tar.gz (49 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2mikkybf/pathlib_a4bf1d49758546149417869b68b0c1ab/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2mikkybf/pathlib_a4bf1d49758546149417869b68b0c1ab/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-armzvq6z
         cwd: /tmp/pip-install-2mikkybf/pathlib_a4bf1d49758546149417869b68b0c1ab/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/__init__.py", line 19, in <module>
        from setuptools.dist import Distribution
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/home/xxxxxx/o3de/python/runtime/python-3.7.10-rev2-linux/python/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz#sha256=6940718dfc3eff4258203ad5021090933e5c04707d5ca8cc9e73c94a7894ea9f (from https://pypi.org/simple/pathlib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pathlib==1.0.1
ERROR: No matching distribution found for pathlib==1.0.1
 - use CMAKE_MESSAGE_LOG_LEVEL to VERBOSE for more information
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/AWSGameLiftServerSDK-3.4.1-rev1-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/libsamplerate-0.2.1-rev2-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/NvCloth-v1.1.6-4-gd243404-pr58-rev1-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev3-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/poly2tri-7f0487a-rev1-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/v-hacd-2.3-1a49edf-rev1-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/mikkelsen-1.0.0.4-linux
-- Using package /home/xxxxxx/.o3de/3rdParty/packages/unwind-1.2.1-linux
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxxxxx/o3de/build/linux_ninja
```

build compilation is successful but still does not open in o3de editor above screenshot

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: OpenSUSE
 - Version: Tumbleweed
 -  CPU: AMD 3 3100
 - GPU: AMD 5500 XT
 - Memory: 16GB

**Additional context**

**Comment by Mobs1024** [comment]
installed from https://software.opensuse.org/package/libffi6 works good,didn't look officially in the doc.
