### ISSUE TITLE
CMake Configure Fails if Net Auto-Components are Enabled, but No Auto-Components are Created

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#4058]
**Describe the bug**
Configure fails if autocomponents are enabled, but no autocomponents are created yet

**To Reproduce**
1. Create a new gem
2. This gem will include network components so follow the steps here under Build setup: https://o3de.org/docs/user-guide/gems/reference/multiplayer/multiplayer/configuration/
3. After editing cmake to allow for autocomponent, configure your project
*.AutoComponent.xml,AutoComponentTypes_Header.jinja,$path/AutoComponentTypes.h : error Processing expansion rule
An unexpected error occurred, please report the error you encountered and include your build output
Traceback (most recent call last):
  File "C:/prj/o3de/cmake/AzAutoGen.py", line 372, in <module>
    autoGenResult = ExecuteExpansionRules(cacheDir, outputDir, projectDir, inputFiles, expansionRules, dryrun, verbose, dataInputSet, outputFiles)
  File "C:/prj/o3de/cmake/AzAutoGen.py", line 326, in ExecuteExpansionRules
    ProcessExpansionRule(sourceFiles, templateFiles, templateCache, outputDir, projectDir, expansionRule, dryrun, verbose, dataInputSet, outputFiles)
  File "C:/prj/o3de/cmake/AzAutoGen.py", line 292, in ProcessExpansionRule
    outputFileAbsolute = outputFile.replace("$path", ComputeOutputPath(dataInputFiles, projectDir, outputDir))
UnboundLocalError: local variable 'dataInputFiles' referenced before assignment
CMake Error at C:/prj/o3de/cmake/LyAutoGen.cmake:34 (add_custom_command):
  add_custom_command Wrong syntax.  A TARGET or OUTPUT must be specified.
Call Stack (most recent call first):
  C:/prj/o3de/cmake/LYWrappers.cmake:378 (ly_add_autogen)
  C:/prj/o3de/Gems/MultiplayerPhysX/Code/CMakeLists.txt:18 (ly_add_target)

**Expected behavior**
cmake configure should work even if users haven't created their first autocomponent yet

**Work Around**
Add a new autocomponent and add it to your <mygem>_files.cmake

**Desktop/Device (please complete the following information):**
 - Device: .PC,
 - OS:Windows

**Comment by ppinfel** [comment]
the doc link doesnt work

**Comment by AMZN-Gene** [comment]
thanks! updated with new link

**Comment by AMZN-Gene** [comment]
I'm in the process of updating the multiplayer gem build setup doc to include the workaround...
https://www.o3de.org/docs/user-guide/gems/reference/multiplayer/multiplayer-gem/configuration/

**Comment by lmbr-pip** [comment]
SIG-Network triage, removing SIG-network label as this is auto-gen issue not specific to networking.
