### ISSUE TITLE
[SliceDeprecation] Convert ScriptCanvas/UI related automated tests to use prefab system

### ISSUE THREAD

**Issue by chiyenteng** [o3de/o3de#7329]
In order to prevent using prefab system(Get rid of **enable_prefab_system=False**). Convert all level and slice files used in the following automated tests into prefab format:

- Pane_HappyPath_OpenCloseSuccessfully
- Pane_HappyPath_DocksProperly
- Pane_HappyPath_ResizesProperly
- ScriptCanvas_TwoComponents_InteractSuccessfully
- ScriptCanvas_ChangingAssets_ComponentStable
- Graph_HappyPath_ZoomInZoomOut
- NodePalette_HappyPath_CanSelectNode
- ScriptCanvasComponent_OnEntityActivatedDeactivated_PrintMessage
- NodePalette_HappyPath_ClearSelection
- ScriptCanvas_TwoEntities_UseSimultaneously
- ScriptEvent_HappyPath_CreatedWithoutError
- ScriptCanvasTools_Toggle_OpenCloseSuccess
- NodeInspector_HappyPath_VariableRenames
- Debugger_HappyPath_TargetMultipleGraphs
- Debugger_HappyPath_TargetMultipleEntities
- EditMenu_Default_UndoRedo
- Pane_Undocked_ClosesSuccessfully
- Entity_HappyPath_AddScriptCanvasComponent
- Pane_Default_RetainOnSCRestart
- ScriptEvents_HappyPath_SendReceiveAcrossMultiple
- ScriptEvents_Default_SendReceiveSuccessfully
- ScriptEvents_ReturnSetType_Successfully
- NodeCategory_ExpandOnClick
- NodePalette_SearchText_Deletion
- VariableManager_UnpinVariableType_Works
- Node_HappyPath_DuplicateNode
- ScriptEvent_AddRemoveParameter_ActionsSuccessful
- test_FileMenu_Default_NewAndOpen
- test_NewScriptEventButton_HappyPath_ContainsSCCategory
- test_GraphClose_Default_SavePrompt
- test_VariableManager_Default_CreateDeleteVars
- test_Pane_PropertiesChanged_RetainsOnRestart
- test_ScriptEvent_AddRemoveMethod_UpdatesInSC
- test_ScriptEvents_AllParamDatatypes_CreationSuccess
- Opening_Closing_Pane

Test Conversion Procedure Suggested:

- Search the target test script to see which ".slice" files are used in the test, and use the converter tool to convert those files to ".prefab" files. Remember to also change the script to use the converted prefab files instead.
- Open the test level used by target test script, list slice assets used by slice instances in the test level, and convert them into prefab ones with the converter tool.
- Convert the test level file("*.ly") into prefab file format by using the converter tool.
- Replace words related to slice terminology to prefab one.
- Run the converted test locally to see if the target test passed or not.
- If tests failed/can't run, make any changes needed.

Note: Make sure to use prefab system(DON'T use **enable_prefab_system** = False) while adding new automated tests.

**Comment by chiyenteng** [comment]
Was able to convert the tests listed above, but few of the tests failed even without converting have similar error messages:
- NodePalette_HappyPath_CanSelectNode
- Debugger_HappyPath_TargetMultipleEntities
- NodeCategory_ExpandOnClick
- Node_HappyPath_DuplicateNode
- VariableManager_Default_CreateDeleteVars

Error messages(All similar to **TypeError: 'PySide2.Qt\*' called with wrong argument types...**):
```
Report:
EXCEPTION raised:
  Traceback (most recent call last):
    File "D:\ly\o3de\o3de\AutomatedTesting\Gem\PythonTests\scripting/../EditorPythonTestTools/editor_python_test_tools\utils.py", line 308, in start_test
      test_function()
    File "D:/ly/o3de/o3de/AutomatedTesting/Gem/PythonTests/scripting/NodePalette_HappyPath_CanSelectNode.py", line 74, in NodePalette_HappyPath_CanSelectNode
      tree.scrollTo(category_index)
  TypeError: 'PySide2.QtWidgets.QTreeView.scrollTo' called with wrong argument types:
    PySide2.QtWidgets.QTreeView.scrollTo(NoneType)
  Supported signatures:
    PySide2.QtWidgets.QTreeView.scrollTo(PySide2.QtCore.QModelIndex, PySide2.QtWidgets.QAbstractItemView.ScrollHint = PySide2.QtWidgets.QAbstractItemView.ScrollHint.EnsureVisible)
Test result:  FAILURE
```

Also, in `AutomatedTesting\Gem\PythonTests\scripting\TestSuite_Sandbox.py`, there's a test `test_Opening_Closing_Pane`, but it is completely broken since test file `Opening_Closing_Pane.py` is missing. Either add it back or just remove `scripting\TestSuite_Sandbox.py` file.

Created https://github.com/o3de/o3de/issues/7448 for the fix in the future.

**Comment by chiyenteng** [comment]
PR for the conversion: https://github.com/o3de/o3de/pull/7416
