### ISSUE TITLE
In-Memory Spawnables don't work by default in the Editor

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#9016]
**Describe the bug**
When trying to run a python automated test script inside the editor, it fails in CreateInMemorySpawnableAsset because the processing stack isn't enabled by default.

**Steps to reproduce**
1. Run the Editor with the AutomatedTesting project enabled.
2. Load the auto_test level.
3. In the console, run `pyRunFile D:\github\o3de\AutomatedTesting\Gem\PythonTests\largeworlds\dyn_veg\EditorScripts\ShapeIntersectionFilter_InstancesPlantInAssignedShape.py`
(Change the path to the appropriate one for your system setup)

**Expected behavior**
Test runs successfully, ending with a loaded level containing vegetation instances.
![image](https://user-images.githubusercontent.com/82224783/164045611-b6aa52e4-a3b1-4a3c-a1fa-9b513c076524.png)

**Actual behavior**
Test fails with the following:
```
EXCEPTION raised:
  Traceback (most recent call last):
    File "d:\github\o3de\automatedtesting\gem\pythontests\editorpythontesttools\editor_python_test_tools\utils.py", line 307, in start_test
      test_function()
    File "D:/github/o3de/AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/ShapeIntersectionFilter_InstancesPlantInAssignedShape.py", line 74, in ShapeIntersectionFilter_InstancesPlantInAssignedShape
      pink_flower_prefab)
    File "D:\github\o3de\AutomatedTesting\Gem\Editor\Scripts/../../PythonTests\largeworlds\large_worlds_utils\editor_dynveg_test_helper.py", line 119, in create_temp_prefab_vegetation_area
      f"Prefab operation 'CreateInMemorySpawnableAssets' failed. Error: {create_spawnable_result.GetError()}"
  AssertionError: Prefab operation 'CreateInMemorySpawnableAssets' failed. Error: Failed to activate Spawnable Asset Container
Test result:  FAILURE
JSON_START({"name": "ShapeIntersectionFilter_InstancesPlantInAssignedShape", "success": false, "exception": "Traceback (most recent call last):\n    File \"d:\\github\\o3de\\automatedtesting\\gem\\pythontests\\editorpythontesttools\\editor_python_test_tools\\utils.py\", line 307, in start_test\n      test_function()\n    File \"D:/github/o3de/AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/ShapeIntersectionFilter_InstancesPlantInAssignedShape.py\", line 74, in ShapeIntersectionFilter_InstancesPlantInAssignedShape\n      pink_flower_prefab)\n    File \"D:\\github\\o3de\\AutomatedTesting\\Gem\\Editor\\Scripts/../../PythonTests\\largeworlds\\large_worlds_utils\\editor_dynveg_test_helper.py\", line 119, in create_temp_prefab_vegetation_area\n      f\"Prefab operation 'CreateInMemorySpawnableAssets' failed. Error: {create_spawnable_result.GetError()}\"\n  AssertionError: Prefab operation 'CreateInMemorySpawnableAssets' failed. Error: Failed to activate Spawnable Asset Container", "output": "Test ShapeIntersectionFilter_InstancesPlantInAssignedShape finished.\nReport:\nEXCEPTION raised:\n  Traceback (most recent call last):\n    File \"d:\\github\\o3de\\automatedtesting\\gem\\pythontests\\editorpythontesttools\\editor_python_test_tools\\utils.py\", line 307, in start_test\n      test_function()\n    File \"D:/github/o3de/AutomatedTesting/Gem/PythonTests/largeworlds/dyn_veg/EditorScripts/ShapeIntersectionFilter_InstancesPlantInAssignedShape.py\", line 74, in ShapeIntersectionFilter_InstancesPlantInAssignedShape\n      pink_flower_prefab)\n    File \"D:\\github\\o3de\\AutomatedTesting\\Gem\\Editor\\Scripts/../../PythonTests\\largeworlds\\large_worlds_utils\\editor_dynveg_test_helper.py\", line 119, in create_temp_prefab_vegetation_area\n      f\"Prefab operation 'CreateInMemorySpawnableAssets' failed. Error: {create_spawnable_result.GetError()}\"\n  AssertionError: Prefab operation 'CreateInMemorySpawnableAssets' failed. Error: Failed to activate Spawnable Asset Container\nTest result:  FAILURE"})JSON_END
```

**Found in Branch**
Development.

**Additional context**
The problem can be worked around by creating a file named `prefab.editor.setreg` in the AutomatedTesting\user\Registry folder with the following content:
```
{
    "Amazon":
    {
        "Tools":
        {
            "Prefab":
            {
                "Processing":
                {
                    "Stack": {
                        "IntegrationTests": 
                        [
                            { "$type": "AzToolsFramework::Prefab::PrefabConversionUtils::EditorInfoRemover" },
                            { "$type": "AzToolsFramework::Prefab::PrefabConversionUtils::PrefabCatchmentProcessor" }
                        ]
                    }
                }
            }
        }
    }
}
```

**Comment by srikappa-amzn** [comment]
@chiyenteng , these changes look related to [your PR ](https://github.com/o3de/o3de/pull/6179/files)for supporting in-memory spawnables. Can you take a look at this and make the required changes to support running automated tests in the editor too?
