### ISSUE TITLE
AR Bug Report - test_Multiplayer_BasicConnectivity_Connects

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#9105]
**Describe the bug**

`test_Multiplayer_BasicConnectivity_Connects` failed

**Failed Jenkins Job Information:**

Name: Linux [profile_nounity_pipe] - test_profile_nounity
Job Build Number: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-8131/3/pipeline/715

```
[2022-04-21T19:48:18.338Z] =================================== FAILURES ===================================
[2022-04-21T19:48:18.338Z] _ TestAutomation.test_Multiplayer_BasicConnectivity_Connects[linux-crash_log_watchdog0-windows_editor-AutomatedTesting] _
[2022-04-21T19:48:18.338Z] ../../../../../../Tools/LyTestTools/ly_test_tools/o3de/editor_test.py:440: in single_run
[2022-04-21T19:48:18.338Z]     self._run_single_test(request, workspace, editor, editor_test_data, test_spec)
[2022-04-21T19:48:18.338Z] ../../../../../../Tools/LyTestTools/ly_test_tools/o3de/editor_test.py:1007: in _run_single_test
[2022-04-21T19:48:18.338Z]     self._report_result(test_name, test_result)
[2022-04-21T19:48:18.338Z] ../../../../../../Tools/LyTestTools/ly_test_tools/o3de/editor_test.py:756: in _report_result
[2022-04-21T19:48:18.338Z]     pytest.fail(error_str)
[2022-04-21T19:48:18.339Z] E   Failed: Test test_Multiplayer_BasicConnectivity_Connects:
[2022-04-21T19:48:18.339Z] E   Test FAILED
[2022-04-21T19:48:18.339Z] E   ------------
[2022-04-21T19:48:18.339Z] E   |  Output  |
[2022-04-21T19:48:18.339Z] E   ------------
[2022-04-21T19:48:18.339Z] E   Starting test Multiplayer_BasicConnectivity_Connects...
[2022-04-21T19:48:18.339Z] E   Test Multiplayer_BasicConnectivity_Connects finished.
[2022-04-21T19:48:18.339Z] E   Report:
[2022-04-21T19:48:18.339Z] E   [SUCCESS] Success: Unexpected line not found: LaunchEditorServer failed! The ServerLauncher binary is missing!
[2022-04-21T19:48:18.339Z] E   [SUCCESS] Success: Found expected line: Editor has connected to the editor-server.
[2022-04-21T19:48:18.339Z] E   [SUCCESS] Success: Found expected line: Editor is sending the editor-server the level data packet.
[2022-04-21T19:48:18.339Z] E   [SUCCESS] Success: Found expected line: Logger: Editor Server completed receiving the editor's level assets, responding to Editor...
[2022-04-21T19:48:18.339Z] E   [SUCCESS] Success: Found expected line: Editor-server ready. Editor has successfully connected to the editor-server's network simulation.
[2022-04-21T19:48:18.339Z] E   [FAILED ] Failure: Failed to enter game mode
[2022-04-21T19:48:18.339Z] E   EXCEPTION raised:
[2022-04-21T19:48:18.339Z] E     Traceback (most recent call last):
[2022-04-21T19:48:18.339Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 305, in start_test
[2022-04-21T19:48:18.339Z] E         test_function()
[2022-04-21T19:48:18.339Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_BasicConnectivity_Connects.py", line 52, in Multiplayer_BasicConnectivity_Connects
[2022-04-21T19:48:18.339Z] E         helper.multiplayer_enter_game_mode(TestConstants.enter_game_mode)
[2022-04-21T19:48:18.339Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 183, in multiplayer_enter_game_mode
[2022-04-21T19:48:18.339Z] E         Report.critical_result(msgtuple_success_fail, multiplayer.PythonEditorFuncs_is_in_game_mode())
[2022-04-21T19:48:18.339Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 410, in critical_result
[2022-04-21T19:48:18.339Z] E         TestHelper.fail_fast(fast_fail_message)
[2022-04-21T19:48:18.339Z] E       File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 213, in fail_fast
[2022-04-21T19:48:18.339Z] E         raise FailFast()
[2022-04-21T19:48:18.339Z] E     editor_python_test_tools.utils.FailFast
[2022-04-21T19:48:18.339Z] E   Test result:  FAILURE
[2022-04-21T19:48:18.339Z] E   JSON_START({"name": "Multiplayer_BasicConnectivity_Connects", "success": false, "exception": "Traceback (most recent call last):\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py\", line 305, in start_test\n      test_function()\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_BasicConnectivity_Connects.py\", line 52, in Multiplayer_BasicConnectivity_Connects\n      helper.multiplayer_enter_game_mode(TestConstants.enter_game_mode)\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py\", line 183, in multiplayer_enter_game_mode\n      Report.critical_result(msgtuple_success_fail, multiplayer.PythonEditorFuncs_is_in_game_mode())\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py\", line 410, in critical_result\n      TestHelper.fail_fast(fast_fail_message)\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py\", line 213, in fail_fast\n      raise FailFast()\n  editor_python_test_tools.utils.FailFast", "output": "Test Multiplayer_BasicConnectivity_Connects finished.\nReport:\n[SUCCESS] Success: Unexpected line not found: LaunchEditorServer failed! The ServerLauncher binary is missing!\n[SUCCESS] Success: Found expected line: Editor has connected to the editor-server.\n[SUCCESS] Success: Found expected line: Editor is sending the editor-server the level data packet.\n[SUCCESS] Success: Found expected line: Logger: Editor Server completed receiving the editor's level assets, responding to Editor...\n[SUCCESS] Success: Found expected line: Editor-server ready. Editor has successfully connected to the editor-server's network simulation.\n[FAILED ] Failure: Failed to enter game mode\nEXCEPTION raised:\n  Traceback (most recent call last):\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py\", line 305, in start_test\n      test_function()\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/Multiplayer/tests/Multiplayer_BasicConnectivity_Connects.py\", line 52, in Multiplayer_BasicConnectivity_Connects\n      helper.multiplayer_enter_game_mode(TestConstants.enter_game_mode)\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py\", line 183, in multiplayer_enter_game_mode\n      Report.critical_result(msgtuple_success_fail, multiplayer.PythonEditorFuncs_is_in_game_mode())\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py\", line 410, in critical_result\n      TestHelper.fail_fast(fast_fail_message)\n    File \"/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py\", line 213, in fail_fast\n      raise FailFast()\n  editor_python_test_tools.utils.FailFast\nTest result:  FAILURE"})JSON_END
```

**Attachments**

[log.txt](https://github.com/o3de/o3de/files/8540919/log.txt)

**Comment by AMZN-Gene** [comment]
Occurred again today
https://jenkins.build.o3de.org/job/O3DE/view/change-requests/job/PR-9578/2/execution/node/622/log/

**Comment by hultonha** [comment]
I haven't looked into this but do we know if this is failing because of a crash? With the Physics tests we recently switched to using 'Batched' instead of 'Parallel' tests to try and isolate some of the legitimate flaky tests. This might be something worth experimenting with on the networking side potentially to if running the tests in parallel could be contributing to the various flaky failures

**Comment by AMZN-Gene** [comment]
Sorry @hultonha. Ignore my comment from yesterday. Yesterdays instance wasn’t flaky, it actually caught a breaking change. The logger changed, instead of posting “Logger: something something” it posted “System: something something” so the test was looking for the wrong log line.

**Comment by lmbr-pip** [comment]
@hultonha - We have not gotten any recent reports on this test being flakey, any objects to clostng?

**Comment by hultonha** [comment]
Hey @lmbr-pip , thanks for letting me know. Yes sure thing, maybe this was a Jenkins/infrastructure issue after all, I'm happy to close this for now (we can always re-open in future if need be). Thanks!
