### ISSUE TITLE
AR Bug Report: Collider_TriggerPassThrough periodically fails AR

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#9579]
**Describe the bug**
Collider_TriggerPassThrough fails with the following information

Platform: linux

````
Failed: Test Collider_TriggerPassThrough:
Test FAILED
------------
|  Output  |
------------
Test Collider_TriggerPassThrough finished.
Report:
[SUCCESS] Success: Entered game mode
[SUCCESS] Success: Sphere found and validated
[SUCCESS] Success: Trigger Box found and validated
[SUCCESS] Success: Physical Box found and validated
[SUCCESS] Success: Gravity is disabled on Sphere
[SUCCESS] Success: Sphere has positive initial x-velocity
[SUCCESS] Success: Sphere entered Trigger Box
[SUCCESS] Success: Sphere exited Trigger Box
[FAILED ] Failure: Sphere did not pass through Trigger Box
EXCEPTION raised:
  Traceback (most recent call last):
    File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 305, in start_test
      test_function()
    File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_TriggerPassThrough.py", line 214, in Collider_TriggerPassThrough
      Report.critical_result(Tests.sphere_passed_through_trigger_box, sphere.passed_through_trigger_target)
    File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 410, in critical_result
      TestHelper.fail_fast(fast_fail_message)
    File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 213, in fail_fast
      raise FailFast()
  editor_python_test_tools.utils.FailFast
Test result:  FAILURE
````

Editor log

````
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - Info: Entering game mode
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - 
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  Disable Accelerators
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  Entered game mode
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - Success: Entered game mode
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - 
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - Info: Sphere's velocity:
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - 
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - Info:    x: 29.65, y: 0.00, z: 0.00
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - 
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - Success: Sphere found and validated
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - 
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - Success: Trigger Box found and validated
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - 
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - Success: Physical Box found and validated
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - 
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - Success: Gravity is disabled on Sphere
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - 
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - Success: Sphere has positive initial x-velocity
[2022-05-16T18:11:55.714Z] E   [editor_test.log]  (python_test) - 
(python_test) - Info: Sphere's position:
(python_test) - 
(python_test) - Info:    x: 44.44, y: 36.00, z: 36.00
(python_test) - 
[Error] (python) - Python callback threw an exception TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

At:
  /data/workspace/o3de/AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_TriggerPassThrough.py(154): on_trigger_exit
  /data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py(231): wait_for_condition
  /data/workspace/o3de/AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_TriggerPassThrough.py(206): Collider_TriggerPassThrough
  /data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py(305): start_test
  /data/workspace/o3de/AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_TriggerPassThrough.py(233): <module>
(python_test) - Info: Sphere's velocity:
(python_test) - 
(python_test) - Info:    x: -14.70, y: 0.00, z: 0.00
(python_test) - 
(python_test) - Info: Sphere's position:
(python_test) - 
(python_test) - Info:    x: 45.91, y: 36.00, z: 36.00
(python_test) - 
(python_test) - Info: Physical Box's position:
(python_test) - 
(python_test) - Info:    x: 48.00, y: 36.00, z: 35.00
(python_test) - 
(python_test) - Info: Sphere's position:
(python_test) - 
(python_test) - Info:    x: 43.96, y: 36.00, z: 36.00
(python_test) - 
(python_test) - Success: Sphere entered Trigger Box
(python_test) - 
(python_test) - Success: Sphere exited Trigger Box
(python_test) - 
(python_test) - Failure: Sphere did not pass through Trigger Box
(python_test) - 
(python_test) - Test Collider_TriggerPassThrough finished.
Report:
[SUCCESS] Success: Entered game mode
[SUCCESS] Success: Sphere found and validated
[SUCCESS] Success: Trigger Box found and validated
[SUCCESS] Success: Physical Box found and validated
[SUCCESS] Success: Gravity is disabled on Sphere
[SUCCESS] Success: Sphere has positive initial x-velocity
[SUCCESS] Success: Sphere entered Trigger Box
[SUCCESS] Success: Sphere exited Trigger Box
[FAILED ] Failure: Sphere did not pass through Trigger Box
EXCEPTION raised:
  Traceback (most recent call last):
    File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 305, in start_test
      test_function()
    File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/Physics/tests/collider/Collider_TriggerPassThrough.py", line 214, in Collider_TriggerPassThrough
      Report.critical_result(Tests.sphere_passed_through_trigger_box, sphere.passed_through_trigger_target)
    File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 410, in critical_result
      TestHelper.fail_fast(fast_fail_message)
    File "/data/workspace/o3de/AutomatedTesting/Gem/PythonTests/EditorPythonTestTools/editor_python_test_tools/utils.py", line 213, in fail_fast
      raise FailFast()
  editor_python_test_tools.utils.FailFast
Test result:  FAILURE
````

**Comment by hultonha** [comment]
Reviewed this in sig-simulation triage. Bumping to Critical as this is a flaky test we want to get fixed ASAP. Thanks for looking into this @FuzzyCarterAWS

**Comment by hultonha** [comment]
Downgrading to major as these have a all temporarily disabled. The are being reviewed and will be restored after validating they are still useful and no longer flaky.

**Comment by moraaar** [comment]
All physics tests are going through a major refactor and all these tests won't be used. Closing this bug.
Tagging @hultonha @FuzzyCarterAWS
