### ISSUE TITLE
Re-enable Spawnable tests.

### ISSUE THREAD

**Issue by AMZN-mnaumov** [o3de/o3de#9789]
Lua spawnable integration tests are currently broken on Linux because of an unknown intermittent issue.
https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/development/2409/pipeline

**Comment by jckand-amzn** [comment]
Re-opening as tests still intermittently fail on both Windows and Linux.

**Comment by jckand-amzn** [comment]
Ran the Prefab test suite 100x on both Windows and Linux with 0 local failures. @chiyenteng has encountered failures when running locally, and on AR.

**Comment by chiyenteng** [comment]
On AR: https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/PR-9933/3/pipeline/665

**Comment by chiyenteng** [comment]
E   [editor_test.log]  <10:31:11> (python_test) -
E   [editor_test.log]  <10:31:11> (python_test) - Info: Spawned Entity Scale: Found 8.889683573327787e-18, expected 5.0
E   [editor_test.log]  <10:31:11> (python_test) -
E   [editor_test.log]  <10:31:11> (python_test) - Info: Spawned Entity Scale: Found 8.889683573327787e-18, expected 5.0
E   [editor_test.log]  <10:31:11> (python_test) -
E   [editor_test.log]  <10:31:11> (python_test) - Test Lua_Spawnables_NestedSpawn finished.
E   [editor_test.log]  Report:
E   [editor_test.log]  EXCEPTION raised:
E   [editor_test.log]    Traceback (most recent call last):
E   [editor_test.log]      File "d:\ly\o3de\o3de\automatedtesting\gem\pythontests\editorpythontesttools\editor_python_test_tools\utils.py", line 305, in start_test
E   [editor_test.log]        test_function()
E   [editor_test.log]      File "D:/ly/o3de/o3de/AutomatedTesting/Gem/PythonTests/Prefab/tests/spawnables/Lua_Spawnables_NestedSpawn.py", line 57, in Lua_Spawnables_NestedSpawn
E   [editor_test.log]        expected_spawned_entity_scale)
E   [editor_test.log]      File "D:\ly\o3de\o3de\AutomatedTesting\Gem\Editor\Scripts/../../PythonTests\Prefab\tests\PrefabTestUtils.py", line 301, in validate_spawned_entity_transform
E   [editor_test.log]        f"Entity was not spawned in the position expected: Found {entity.get_world_translation()}, " \
E   [editor_test.log]    AssertionError: Entity was not spawned in the position expected: Found (x=0.0000000,y=0.0000000,z=0.0000000), expected (x=5.0000000,y=0.0000000,z=0.0000000)
E   [editor_test.log]  Test result:  FAILURE
E   [editor_test.log]  JSON_START({"name": "Lua_Spawnables_NestedSpawn", "success": false, "exception": "Traceback (most recent call last):\n    File \"d:\\ly\\o3de\\o3de\\automatedtesting\\gem\\pythontests\\editorpythontesttools\\editor_python_test_tools\\utils.py\", line 305, in start_test\n      test_function()\n    File \"D:/ly/o3de/o3de/AutomatedTesting/Gem/PythonTests/Prefab/tests/spawnables/Lua_Spawnables_NestedSpawn.py\", line 57, in Lua_Spawnables_NestedSpawn\n      expected_spawned_entity_scale)\n    File \"D:\\ly\\o3de\\o3de\\AutomatedTesting\\Gem\\Editor\\Scripts/../../PythonTests\\Prefab\\tests\\PrefabTestUtils.py\", line 301, in validate_spawned_entity_transform\n      f\"Entity was not spawned in the position expected: Found {entity.get_world_translation()}, \" \\\n  AssertionError: Entity was not spawned in the position expected: Found (x=0.0000000,y=0.0000000,z=0.0000000), expected (x=5.0000000,y=0.0000000,z=0.0000000)", "output": "Test Lua_Spawnables_NestedSpawn finished.\nReport:\nEXCEPTION raised:\n  Traceback (most recent call last):\n    File \"d:\\ly\\o3de\\o3de\\automatedtesting\\gem\\pythontests\\editorpythontesttools\\editor_python_test_tools\\utils.py\", line 305, in start_test\n      test_function()\n    File \"D:/ly/o3de/o3de/AutomatedTesting/Gem/PythonTests/Prefab/tests/spawnables/Lua_Spawnables_NestedSpawn.py\", line 57, in Lua_Spawnables_NestedSpawn\n      expected_spawned_entity_scale)\n    File \"D:\\ly\\o3de\\o3de\\AutomatedTesting\\Gem\\Editor\\Scripts/../../PythonTests\\Prefab\\tests\\PrefabTestUtils.py\", line 301, in validate_spawned_entity_transform\n      f\"Entity was not spawned in the position expected: Found {entity.get_world_translation()}, \" \\\n  AssertionError: Entity was not spawned in the position expected: Found (x=0.0000000,y=0.0000000,z=0.0000000), expected (x=5.0000000,y=0.0000000,z=0.0000000)\nTest result:  FAILURE"})JSON_END

**Comment by srikappa-amzn** [comment]
Bumping to critical since these tests shouldn't be left in a disabled state.
